
package nl.hu.iac.webshop.soap.acceptgiro.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AcceptgiroServiceImplService", targetNamespace = "http://service.acceptgiro/", wsdlLocation = "http://localhost:8081/soap?wsdl")
public class AcceptgiroServiceImplService
    extends Service
{

    private final static URL ACCEPTGIROSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException ACCEPTGIROSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName ACCEPTGIROSERVICEIMPLSERVICE_QNAME = new QName("http://service.acceptgiro/", "AcceptgiroServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8081/soap?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ACCEPTGIROSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        ACCEPTGIROSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public AcceptgiroServiceImplService() {
        super(__getWsdlLocation(), ACCEPTGIROSERVICEIMPLSERVICE_QNAME);
    }

    public AcceptgiroServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ACCEPTGIROSERVICEIMPLSERVICE_QNAME, features);
    }

    public AcceptgiroServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, ACCEPTGIROSERVICEIMPLSERVICE_QNAME);
    }

    public AcceptgiroServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ACCEPTGIROSERVICEIMPLSERVICE_QNAME, features);
    }

    public AcceptgiroServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AcceptgiroServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns AcceptgiroServiceImpl
     */
    @WebEndpoint(name = "AcceptgiroServiceImplPort")
    public AcceptgiroServiceImpl getAcceptgiroServiceImplPort() {
        return super.getPort(new QName("http://service.acceptgiro/", "AcceptgiroServiceImplPort"), AcceptgiroServiceImpl.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AcceptgiroServiceImpl
     */
    @WebEndpoint(name = "AcceptgiroServiceImplPort")
    public AcceptgiroServiceImpl getAcceptgiroServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.acceptgiro/", "AcceptgiroServiceImplPort"), AcceptgiroServiceImpl.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ACCEPTGIROSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw ACCEPTGIROSERVICEIMPLSERVICE_EXCEPTION;
        }
        return ACCEPTGIROSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
