
package nl.hu.iac.webshop.soap.acceptgiro.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "AcceptgiroServiceImpl", targetNamespace = "http://service.acceptgiro/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface AcceptgiroServiceImpl {


    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns acceptgiro.service.Acceptgiro
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "doAcceptgiro", targetNamespace = "http://service.acceptgiro/", className = "acceptgiro.service.DoAcceptgiro")
    @ResponseWrapper(localName = "doAcceptgiroResponse", targetNamespace = "http://service.acceptgiro/", className = "acceptgiro.service.DoAcceptgiroResponse")
    @Action(input = "http://service.acceptgiro/AcceptgiroServiceImpl/doAcceptgiroRequest", output = "http://service.acceptgiro/AcceptgiroServiceImpl/doAcceptgiroResponse")
    public Acceptgiro doAcceptgiro(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        double arg2);

}
